export const UI_SET_LOADING = 'UI_SET_LOADING';
export const UI_SET_ERROR = 'UI_SET_ERROR';
export const UI_TYPES = {
  UI_SET_LOADING,
  UI_SET_ERROR
};

export const AUTH_REQUEST_AUTHENTICATE = 'AUTH_REQUEST_AUTHENTICATE';
export const AUTH_RECEIVE_AUTHENTICATE = 'AUTH_RECEIVE_AUTHENTICATE';
export const AUTH_REQUEST_DEAUTHENTICATE = 'AUTH_REQUEST_DEAUTHENTICATE';
export const AUTH_REQUEST_STATUS = 'AUTH_REQUEST_STATUS';
export const AUTH_TYPES = {
  AUTH_REQUEST_AUTHENTICATE,
  AUTH_RECEIVE_AUTHENTICATE,
  AUTH_REQUEST_DEAUTHENTICATE,
  AUTH_REQUEST_STATUS
};

export const ACC_SET_ACCOUNT = 'ACC_SET_ACCOUNT';
export const ACC_REQUEST_ACCOUNT = 'ACC_REQUEST_ACCOUNT';
export const ACC_RECEIVE_ACCOUNT = 'ACC_RECEIVE_ACCOUNT';
export const ACC_REQUEST_ACCOUNT_UPDATE = 'ACC_REQUEST_ACCOUNT_UPDATE';
export const ACC_RECEIVE_ACCOUNT_UPDATE = 'ACC_RECEIVE_ACCOUNT_UPDATE';
export const ACC_TYPES = {
  ACC_SET_ACCOUNT,
  ACC_REQUEST_ACCOUNT,
  ACC_RECEIVE_ACCOUNT,
  ACC_REQUEST_ACCOUNT_UPDATE,
  ACC_RECEIVE_ACCOUNT_UPDATE
};
